export let categories = [
	{
		id: 1,
		category: "Vegetables",
		image: "../assets/images/vegitables.png",
		items: [
			{
				id: 11,
				category: "Vegetables",
				name: "Tomato",
				cost: 2.5,
				description: "Fresh red tomatoes",
				subCategoryName: "Fresh Vegetables",
			},
			{
				id: 12,
				category: "Vegetables",
				name: "Cucumber",
				cost: 1.8,
				description: "Crisp green cucumbers",
				subCategoryName: "Fresh Vegetables",
			},
			{
				id: 13,
				category: "Vegetables",
				name: "Carrot",
				cost: 1.2,
				description: "Sweet and crunchy carrots",
				subCategoryName: "Fresh Vegetables",
			},
			{
				id: 14,
				category: "Vegetables",
				name: "Broccoli",
				cost: 2.0,
				description: "Nutrient-rich broccoli",
				subCategoryName: "Fresh Vegetables",
			},
			{
				id: 15,
				category: "Vegetables",
				name: "Spinach",
				cost: 1.5,
				description: "Fresh green spinach leaves",
				subCategoryName: "Fresh Vegetables",
			},
			{
				id: 16,
				category: "Vegetables",
				name: "Bell Pepper",
				cost: 2.8,
				description: "Colorful bell peppers",
				subCategoryName: "Fresh Vegetables",
			},
			{
				id: 17,
				category: "Vegetables",
				name: "Onion",
				cost: 1.0,
				description: "Sweet and pungent onions",
				subCategoryName: "Fresh Vegetables",
			},
			{
				id: 18,
				category: "Vegetables",
				name: "Potato",
				cost: 1.2,
				description: "Versatile potatoes",
				subCategoryName: "Fresh Vegetables",
			},
			{
				id: 19,
				category: "Vegetables",
				name: "Zucchini",
				cost: 2.2,
				description: "Mild-flavored zucchini",
				subCategoryName: "Fresh Vegetables",
			},
		],
	},
	{
		id: 2,
		category: "Atta",
		image: "../assets/images/atta.png",
		items: [
			{
				id: 21,
				category: "Atta",
				name: "Whole Wheat Flour",
				cost: 3.0,
				description: "Stone-ground whole wheat flour",
				subCategoryName: "Flour",
			},
			{
				id: 22,
				category: "Atta",
				name: "Multigrain Atta",
				cost: 4.5,
				description: "Blend of various grains",
				subCategoryName: "Flour",
			},
			{
				id: 23,
				category: "Atta",
				name: "Besan",
				cost: 2.2,
				description: "Gram flour for culinary use",
				subCategoryName: "Flour",
			},
			{
				id: 24,
				category: "Atta",
				name: "Maida",
				cost: 2.8,
				description: "Refined wheat flour",
				subCategoryName: "Flour",
			},
			{
				id: 25,
				category: "Atta",
				name: "Ragi Flour",
				cost: 3.5,
				description: "Nutritious finger millet flour",
				subCategoryName: "Flour",
			},
			{
				id: 26,
				category: "Atta",
				name: "Chapati Flour",
				cost: 3.2,
				description: "Flour for making chapatis",
				subCategoryName: "Flour",
			},
			{
				id: 27,
				category: "Atta",
				name: "Sooji",
				cost: 2.0,
				description: "Semolina for various dishes",
				subCategoryName: "Flour",
			},
			{
				id: 28,
				category: "Atta",
				name: "Corn Flour",
				cost: 2.5,
				description: "Fine cornflour for cooking",
				subCategoryName: "Flour",
			},
			{
				id: 29,
				category: "Atta",
				name: "Bajra Flour",
				cost: 3.8,
				description: "Pearl millet flour",
				subCategoryName: "Flour",
			},
		],
	},
	{
		id: 3,
		category: "Pulses",
		image: "../assets/images/pulses.png",
		items: [
			{
				id: 31,
				category: "Pulses",
				name: "Lentils",
				cost: 2.0,
				description: "Various types of lentils",
				subCategoryName: "Legumes",
			},
			{
				id: 32,
				category: "Pulses",
				name: "Chickpeas",
				cost: 2.5,
				description: "Nutty-flavored chickpeas",
				subCategoryName: "Legumes",
			},
			{
				id: 33,
				category: "Pulses",
				name: "Black Beans",
				cost: 3.0,
				description: "Rich and hearty black beans",
				subCategoryName: "Legumes",
			},
			{
				id: 34,
				category: "Pulses",
				name: "Kidney Beans",
				cost: 2.8,
				description: "Large and kidney-shaped beans",
				subCategoryName: "Legumes",
			},
			{
				id: 35,
				category: "Pulses",
				name: "Green Peas",
				cost: 2.2,
				description: "Sweet and tender green peas",
				subCategoryName: "Legumes",
			},
			{
				id: 36,
				category: "Pulses",
				name: "Moong Dal",
				cost: 2.3,
				description: "Split and hulled moong beans",
				subCategoryName: "Legumes",
			},
			{
				id: 37,
				category: "Pulses",
				name: "Toor Dal",
				cost: 3.5,
				description: "Yellow pigeon peas",
				subCategoryName: "Legumes",
			},
			{
				id: 38,
				category: "Pulses",
				name: "Urad Dal",
				cost: 3.2,
				description: "Black gram dal",
				subCategoryName: "Legumes",
			},
			{
				id: 39,
				category: "Pulses",
				name: "Masoor Dal",
				cost: 2.7,
				description: "Red lentils",
				subCategoryName: "Legumes",
			},
		],
	},
	{
		id: 4,
		category: "Milk",
		image: "../assets/images/milk.png",
		items: [
			{
				id: 41,
				category: "Milk",
				name: "Full Cream Milk",
				cost: 2.0,
				description: "Rich and creamy whole milk",
				subCategoryName: "Dairy",
			},
			{
				id: 42,
				category: "Milk",
				name: "Skimmed Milk",
				cost: 2.5,
				description: "Low-fat skimmed milk",
				subCategoryName: "Dairy",
			},
			{
				id: 43,
				category: "Milk",
				name: "Chocolate Milk",
				cost: 3.0,
				description: "Sweet and indulgent chocolate-flavored milk",
				subCategoryName: "Dairy",
			},
			{
				id: 44,
				category: "Milk",
				name: "Almond Milk",
				cost: 3.2,
				description: "Nutty and dairy-free almond milk",
				subCategoryName: "Plant-Based",
			},
			{
				id: 45,
				category: "Milk",
				name: "Soy Milk",
				cost: 2.8,
				description: "Protein-rich soy milk",
				subCategoryName: "Plant-Based",
			},
			{
				id: 46,
				category: "Milk",
				name: "Oat Milk",
				cost: 3.5,
				description: "Creamy and lactose-free oat milk",
				subCategoryName: "Plant-Based",
			},
			{
				id: 47,
				category: "Milk",
				name: "Coconut Milk",
				cost: 2.2,
				description: "Rich and tropical coconut milk",
				subCategoryName: "Plant-Based",
			},
			{
				id: 48,
				category: "Milk",
				name: "Condensed Milk",
				cost: 3.8,
				description: "Sweetened condensed milk",
				subCategoryName: "Dairy",
			},
			{
				id: 49,
				category: "Milk",
				name: "Evaporated Milk",
				cost: 3.7,
				description: "Concentrated evaporated milk",
				subCategoryName: "Dairy",
			},
		],
	},
	{
		id: 5,
		category: "Spices",
		image: "../assets/images/spices.png",
		items: [
			{
				id: 51,
				category: "Spices",
				name: "Turmeric Powder",
				cost: 1.5,
				description: "Ground turmeric for flavor and color",
				subCategoryName: "Ground Spices",
			},
			{
				id: 52,
				category: "Spices",
				name: "Cumin Seeds",
				cost: 2.0,
				description: "Whole cumin seeds for cooking",
				subCategoryName: "Whole Spices",
			},
			{
				id: 53,
				category: "Spices",
				name: "Coriander Powder",
				cost: 1.8,
				description: "Ground coriander for seasoning",
				subCategoryName: "Ground Spices",
			},
			{
				id: 54,
				category: "Spices",
				name: "Red Chili Powder",
				cost: 2.2,
				description: "Hot and spicy red chili powder",
				subCategoryName: "Ground Spices",
			},
			{
				id: 55,
				category: "Spices",
				name: "Black Pepper",
				cost: 3.0,
				description: "Freshly ground black pepper",
				subCategoryName: "Whole Spices",
			},
			{
				id: 56,
				category: "Spices",
				name: "Cinnamon Sticks",
				cost: 2.5,
				description: "Aromatic cinnamon sticks",
				subCategoryName: "Whole Spices",
			},
			{
				id: 57,
				category: "Spices",
				name: "Cardamom Pods",
				cost: 4.0,
				description: "Sweet and fragrant cardamom pods",
				subCategoryName: "Whole Spices",
			},
			{
				id: 58,
				category: "Spices",
				name: "Cloves",
				cost: 3.5,
				description: "Spicy and pungent cloves",
				subCategoryName: "Whole Spices",
			},
			{
				id: 59,
				category: "Spices",
				name: "Mustard Seeds",
				cost: 2.3,
				description: "Tiny and powerful mustard seeds",
				subCategoryName: "Whole Spices",
			},
		],
	},
	{
		id: 6,
		category: "Oil",
		image: "../assets/images/oil.png",
		items: [
			{
				id: 61,
				category: "Oil",
				name: "Olive Oil",
				cost: 5.0,
				description: "Extra virgin olive oil",
				subCategoryName: "Cooking Oils",
			},
			{
				id: 62,
				category: "Oil",
				name: "Vegetable Oil",
				cost: 3.0,
				description: "Versatile vegetable cooking oil",
				subCategoryName: "Cooking Oils",
			},
			{
				id: 63,
				category: "Oil",
				name: "Canola Oil",
				cost: 4.0,
				description: "Low-cholesterol canola oil",
				subCategoryName: "Cooking Oils",
			},
			{
				id: 64,
				category: "Oil",
				name: "Coconut Oil",
				cost: 3.5,
				description: "Fragrant and tropical coconut oil",
				subCategoryName: "Cooking Oils",
			},
			{
				id: 65,
				category: "Oil",
				name: "Sunflower Oil",
				cost: 2.8,
				description: "Light and neutral sunflower oil",
				subCategoryName: "Cooking Oils",
			},
			{
				id: 66,
				category: "Oil",
				name: "Sesame Oil",
				cost: 4.5,
				description: "Toasty and flavorful sesame oil",
				subCategoryName: "Cooking Oils",
			},
			{
				id: 67,
				category: "Oil",
				name: "Peanut Oil",
				cost: 3.2,
				description: "Rich and nutty peanut oil",
				subCategoryName: "Cooking Oils",
			},
			{
				id: 68,
				category: "Oil",
				name: "Avocado Oil",
				cost: 6.0,
				description: "Healthy and monounsaturated avocado oil",
				subCategoryName: "Cooking Oils",
			},
			{
				id: 69,
				category: "Oil",
				name: "Ghee",
				cost: 5.5,
				description: "Clarified butter with a rich aroma",
				subCategoryName: "Cooking Oils",
			},
		],
	},
	{
		id: 7,
		category: "Snacks",
		image: "../assets/images/snacks.png",
		items: [
			{
				id: 71,
				category: "Snacks",
				name: "Potato Chips",
				cost: 2.0,
				description: "Crispy and salty potato chips",
				subCategoryName: "Chips",
			},
			{
				id: 72,
				category: "Snacks",
				name: "Popcorn",
				cost: 1.5,
				description: "Classic movie night popcorn",
				subCategoryName: "Popcorn",
			},
			{
				id: 73,
				category: "Snacks",
				name: "Pretzels",
				cost: 2.2,
				description: "Twisted and salty pretzels",
				subCategoryName: "Savory Snacks",
			},
			{
				id: 74,
				category: "Snacks",
				name: "Trail Mix",
				cost: 3.0,
				description: "A mix of nuts and dried fruits",
				subCategoryName: "Healthy Snacks",
			},
			{
				id: 75,
				category: "Snacks",
				name: "Chocolate Bars",
				cost: 2.8,
				description: "Indulgent chocolate bars",
				subCategoryName: "Sweet Snacks",
			},
			{
				id: 76,
				category: "Snacks",
				name: "Granola Bars",
				cost: 3.5,
				description: "Nutty and wholesome granola bars",
				subCategoryName: "Healthy Snacks",
			},
			{
				id: 77,
				category: "Snacks",
				name: "Cheese Puffs",
				cost: 2.3,
				description: "Cheesy and puffy snacks",
				subCategoryName: "Cheese Snacks",
			},
			{
				id: 78,
				category: "Snacks",
				name: "Dried Fruits",
				cost: 4.0,
				description: "Naturally sweet dried fruits",
				subCategoryName: "Healthy Snacks",
			},
			{
				id: 79,
				category: "Snacks",
				name: "Crackers",
				cost: 2.5,
				description: "Crisp and savory crackers",
				subCategoryName: "Savory Snacks",
			},
		],
	},
	{
		id: 8,
		category: "Beverages",
		image: "../assets/images/beverages.png",
		items: [
			{
				id: 81,
				category: "Beverages",
				name: "Green Tea",
				cost: 3.0,
				description: "Refreshing green tea",
				subCategoryName: "Tea",
			},
			{
				id: 82,
				category: "Beverages",
				name: "Coffee Beans",
				cost: 5.0,
				description: "High-quality coffee beans",
				subCategoryName: "Coffee",
			},
			{
				id: 83,
				category: "Beverages",
				name: "Fruit Juice",
				cost: 3.5,
				description: "Assorted fruit juices",
				subCategoryName: "Juices",
			},
			{
				id: 84,
				category: "Beverages",
				name: "Sports Drink",
				cost: 2.8,
				description: "Hydrating sports drink",
				subCategoryName: "Energy Drinks",
			},
			{
				id: 85,
				category: "Beverages",
				name: "Soda",
				cost: 2.2,
				description: "Carbonated soft drinks",
				subCategoryName: "Carbonated Beverages",
			},
			{
				id: 86,
				category: "Beverages",
				name: "Almond Milk",
				cost: 4.5,
				description: "Nutty and dairy-free almond milk",
				subCategoryName: "Plant-Based Milk",
			},
			{
				id: 87,
				category: "Beverages",
				name: "Coconut Water",
				cost: 3.2,
				description: "Refreshing coconut water",
				subCategoryName: "Healthy Drinks",
			},
			{
				id: 88,
				category: "Beverages",
				name: "Iced Tea",
				cost: 2.5,
				description: "Cool and sweet iced tea",
				subCategoryName: "Tea",
			},
			{
				id: 89,
				category: "Beverages",
				name: "Smoothie Mix",
				cost: 4.0,
				description: "Frozen fruit smoothie mix",
				subCategoryName: "Smoothies",
			},
		],
	},
	{
		id: 9,
		category: "Personal Care",
		image: "../assets/images/personalcare.png",
		items: [
			{
				id: 91,
				category: "Personal Care",
				name: "Shampoo",
				cost: 5.0,
				description: "Cleansing and nourishing shampoo",
				subCategoryName: "Hair Care",
			},
			{
				id: 92,
				category: "Personal Care",
				name: "Toothpaste",
				cost: 2.0,
				description: "Fluoride toothpaste for oral care",
				subCategoryName: "Oral Care",
			},
			{
				id: 93,
				category: "Personal Care",
				name: "Soap Bars",
				cost: 1.8,
				description: "Gentle and moisturizing soap bars",
				subCategoryName: "Body Care",
			},
			{
				id: 94,
				category: "Personal Care",
				name: "Deodorant",
				cost: 3.0,
				description: "Long-lasting deodorant for freshness",
				subCategoryName: "Body Care",
			},
			{
				id: 95,
				category: "Personal Care",
				name: "Hand Sanitizer",
				cost: 2.5,
				description: "Alcohol-based hand sanitizer",
				subCategoryName: "Hygiene",
			},
			{
				id: 96,
				category: "Personal Care",
				name: "Shaving Cream",
				cost: 2.2,
				description: "Smooth and hydrating shaving cream",
				subCategoryName: "Shaving",
			},
			{
				id: 97,
				category: "Personal Care",
				name: "Sunscreen",
				cost: 4.0,
				description: "SPF protection for sun safety",
				subCategoryName: "Skin Care",
			},
		],
	},
];
